### ISSUE TITLE
Question - Are configs synced by default?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [rheimus/ServerSync#10]
#### Issue: Adding configs folder freezes application

<details>
<summary>Logs (serverysync & minecraft)</summary>
<pre>

</pre>
</details>

**Comment by rheimus** [comment]
Nothing is synced by default. The default generated config does have mods set up to sync though.

The current implementation does have an issue with large numbers of files as it does "just in time" file hashing. So it can seemingly freeze for a while when syncing.

Does your freeze eventually resolve after a while or is it just dead completely?

**Comment by P3rf3ctXZer0** [comment]
Freezes completely

**Comment by rheimus** [comment]
File hashing is now done on a per file basis, should not get major freezes anymore. Feel free to reopen if this is not the case though.
