### ISSUE TITLE
Does this work on servers that cannot make the bat file? Can I still just place this in the mods folder?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [rheimus/ServerSync#8]
I got a bisect hosting server because my main server is currently down. (I accidently scorched my cpu and shorted it.)

**Comment by rheimus** [comment]
The forge loaded method of starting the server should still work yeah.

**Comment by rheimus** [comment]
Is there no way to add a line to whatever starts the minecraft server, or is that all controlled by a third party?

**Comment by P3rf3ctXZer0** [comment]
it is all controlled by a 3rd party
